//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR_library
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCode
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
